plugins {
    id 'io.qameta.allure' version '3.0.1'
}

group = 'io.student'
version = '1.0.0'

def allureVersion = '2.32.0'
def aspectJVersion = '1.9.22'
def junitVersion = '6.0.2'
def retrofitVersion = '2.9.0'
def okhttpVersion = '4.12.0'

configurations {
    agent {
        canBeResolved = true
        canBeConsumed = true
    }
}

dependencies {
    agent "org.aspectj:aspectjweaver:$aspectJVersion"

    testImplementation platform("io.qameta.allure:allure-bom:$allureVersion")
    testImplementation "io.qameta.allure:allure-junit5"
    testImplementation "io.qameta.allure:allure-selenide"

    testImplementation platform("org.junit:junit-bom:$junitVersion")
    testImplementation "org.junit.jupiter:junit-jupiter"
    testImplementation "com.codeborne:selenide:7.3.1"
    testImplementation "com.squareup.retrofit2:retrofit:$retrofitVersion"
    testImplementation "com.squareup.retrofit2:converter-jackson:$retrofitVersion"
    testImplementation "com.squareup.okhttp3:okhttp:$okhttpVersion"
    testImplementation "com.squareup.okhttp3:logging-interceptor:$okhttpVersion"
    testCompileOnly "org.projectlombok:lombok:1.18.42"
    testAnnotationProcessor "org.projectlombok:lombok:1.18.42"
}

allure {
    version = allureVersion
}

test {
    useJUnitPlatform()
    jvmArgs = ["-javaagent:${configurations.agent.singleFile}"]
}
