server:
  port: 8081

spring:
  application:
    name: rococo-geo
  datasource:
    url: 'jdbc:mysql://localhost:3306/rococo-geo?serverTimezone=UTC&createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false'
    hikari:
      connection-timeout: 20000
      minimum-idle: 10
      maximum-pool-size: 30
      idle-timeout: 10000
      max-lifetime: 1800000
      auto-commit: true
    username: root
    password: secret
  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-version: 0
    schemas: rococo-geo
    locations: classpath:db/migration
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
    show-sql: true
    generate-ddl: false
    open-in-view: false

logging:
  level:
    io.student.rococo.geo: DEBUG
    org.springframework.web: INFO
