-- Вставляем начальные данные стран (те же, что были в rcc-api)
-- Используем UUID_TO_BIN для генерации UUID в MySQL 8.0+
INSERT INTO country (id, name) VALUES (UUID_TO_BIN(UUID()), 'Австралия');
INSERT INTO country (id, name) VALUES (UUID_TO_BIN(UUID()), 'Австрия');
INSERT INTO country (id, name) VALUES (UUID_TO_BIN(UUID()), 'Азербайджан');
INSERT INTO country (id, name) VALUES (UUID_TO_BIN(UUID()), 'Албания');
INSERT INTO country (id, name) VALUES (UUID_TO_BIN(UUID()), 'Алжир');
INSERT INTO country (id, name) VALUES (UUID_TO_BIN(UUID()), 'Ангола');
INSERT INTO country (id, name) VALUES (UUID_TO_BIN(UUID()), 'Андорра');
INSERT INTO country (id, name) VALUES (UUID_TO_BIN(UUID()), 'Антигуа и Барбуда');
INSERT INTO country (id, name) VALUES (UUID_TO_BIN(UUID()), 'Аргентина');
INSERT INTO country (id, name) VALUES (UUID_TO_BIN(UUID()), 'Армения');
INSERT INTO country (id, name) VALUES (UUID_TO_BIN(UUID()), 'Афганистан');
INSERT INTO country (id, name) VALUES (UUID_TO_BIN(UUID()), 'Багамские Острова');
INSERT INTO country (id, name) VALUES (UUID_TO_BIN(UUID()), 'Бангладеш');
INSERT INTO country (id, name) VALUES (UUID_TO_BIN(UUID()), 'Барбадос');
INSERT INTO country (id, name) VALUES (UUID_TO_BIN(UUID()), 'Бахрейн');
INSERT INTO country (id, name) VALUES (UUID_TO_BIN(UUID()), 'Белиз');
INSERT INTO country (id, name) VALUES (UUID_TO_BIN(UUID()), 'Белоруссия');
INSERT INTO country (id, name) VALUES (UUID_TO_BIN(UUID()), 'Бельгия');
INSERT INTO country (id, name) VALUES (UUID_TO_BIN(UUID()), 'Бенин');
INSERT INTO country (id, name) VALUES (UUID_TO_BIN(UUID()), 'Болгария');
INSERT INTO country (id, name) VALUES (UUID_TO_BIN(UUID()), 'Боливия');
INSERT INTO country (id, name) VALUES (UUID_TO_BIN(UUID()), 'Босния и Герцеговина');
INSERT INTO country (id, name) VALUES (UUID_TO_BIN(UUID()), 'Ботсвана');
INSERT INTO country (id, name) VALUES (UUID_TO_BIN(UUID()), 'Бразилия');
INSERT INTO country (id, name) VALUES (UUID_TO_BIN(UUID()), 'Бруней');
INSERT INTO country (id, name) VALUES (UUID_TO_BIN(UUID()), 'Буркина-Фасо');
INSERT INTO country (id, name) VALUES (UUID_TO_BIN(UUID()), 'Бурунди');
INSERT INTO country (id, name) VALUES (UUID_TO_BIN(UUID()), 'Бутан');
INSERT INTO country (id, name) VALUES (UUID_TO_BIN(UUID()), 'Вануату');
INSERT INTO country (id, name) VALUES (UUID_TO_BIN(UUID()), 'Великобритания');
INSERT INTO country (id, name) VALUES (UUID_TO_BIN(UUID()), 'Венгрия');
INSERT INTO country (id, name) VALUES (UUID_TO_BIN(UUID()), 'Венесуэла');
INSERT INTO country (id, name) VALUES (UUID_TO_BIN(UUID()), 'Восточный Тимор');
INSERT INTO country (id, name) VALUES (UUID_TO_BIN(UUID()), 'Вьетнам');
INSERT INTO country (id, name) VALUES (UUID_TO_BIN(UUID()), 'Габон');
INSERT INTO country (id, name) VALUES (UUID_TO_BIN(UUID()), 'Республика Гаити');
INSERT INTO country (id, name) VALUES (UUID_TO_BIN(UUID()), 'Гайана');
INSERT INTO country (id, name) VALUES (UUID_TO_BIN(UUID()), 'Гамбия');
INSERT INTO country (id, name) VALUES (UUID_TO_BIN(UUID()), 'Гана');
INSERT INTO country (id, name) VALUES (UUID_TO_BIN(UUID()), 'Гватемала');
INSERT INTO country (id, name) VALUES (UUID_TO_BIN(UUID()), 'Гвинея');
INSERT INTO country (id, name) VALUES (UUID_TO_BIN(UUID()), 'Гвинея-Бисау');
INSERT INTO country (id, name) VALUES (UUID_TO_BIN(UUID()), 'Германия');
INSERT INTO country (id, name) VALUES (UUID_TO_BIN(UUID()), 'Гондурас');
INSERT INTO country (id, name) VALUES (UUID_TO_BIN(UUID()), 'Гренада');
INSERT INTO country (id, name) VALUES (UUID_TO_BIN(UUID()), 'Греция');
INSERT INTO country (id, name) VALUES (UUID_TO_BIN(UUID()), 'Грузия');
INSERT INTO country (id, name) VALUES (UUID_TO_BIN(UUID()), 'Дания');
INSERT INTO country (id, name) VALUES (UUID_TO_BIN(UUID()), 'Джибути');
INSERT INTO country (id, name) VALUES (UUID_TO_BIN(UUID()), 'Доминика');
INSERT INTO country (id, name) VALUES (UUID_TO_BIN(UUID()), 'Доминиканская Республика');
INSERT INTO country (id, name) VALUES (UUID_TO_BIN(UUID()), 'Египет');
INSERT INTO country (id, name) VALUES (UUID_TO_BIN(UUID()), 'Замбия');
INSERT INTO country (id, name) VALUES (UUID_TO_BIN(UUID()), 'Зимбабве');
INSERT INTO country (id, name) VALUES (UUID_TO_BIN(UUID()), 'Израиль');
INSERT INTO country (id, name) VALUES (UUID_TO_BIN(UUID()), 'Индия');
INSERT INTO country (id, name) VALUES (UUID_TO_BIN(UUID()), 'Индонезия');
INSERT INTO country (id, name) VALUES (UUID_TO_BIN(UUID()), 'Иордания');
INSERT INTO country (id, name) VALUES (UUID_TO_BIN(UUID()), 'Ирак');
INSERT INTO country (id, name) VALUES (UUID_TO_BIN(UUID()), 'Иран');
INSERT INTO country (id, name) VALUES (UUID_TO_BIN(UUID()), 'Ирландия');
INSERT INTO country (id, name) VALUES (UUID_TO_BIN(UUID()), 'Исландия');
INSERT INTO country (id, name) VALUES (UUID_TO_BIN(UUID()), 'Испания');
INSERT INTO country (id, name) VALUES (UUID_TO_BIN(UUID()), 'Италия');
INSERT INTO country (id, name) VALUES (UUID_TO_BIN(UUID()), 'Йемен');
INSERT INTO country (id, name) VALUES (UUID_TO_BIN(UUID()), 'Кабо-Верде');
INSERT INTO country (id, name) VALUES (UUID_TO_BIN(UUID()), 'Казахстан');
INSERT INTO country (id, name) VALUES (UUID_TO_BIN(UUID()), 'Камбоджа');
INSERT INTO country (id, name) VALUES (UUID_TO_BIN(UUID()), 'Камерун');
INSERT INTO country (id, name) VALUES (UUID_TO_BIN(UUID()), 'Канада');
INSERT INTO country (id, name) VALUES (UUID_TO_BIN(UUID()), 'Катар');
INSERT INTO country (id, name) VALUES (UUID_TO_BIN(UUID()), 'Кения');
INSERT INTO country (id, name) VALUES (UUID_TO_BIN(UUID()), 'Республика Кипр');
INSERT INTO country (id, name) VALUES (UUID_TO_BIN(UUID()), 'Киргизия');
INSERT INTO country (id, name) VALUES (UUID_TO_BIN(UUID()), 'Кирибати');
INSERT INTO country (id, name) VALUES (UUID_TO_BIN(UUID()), 'Китай');
INSERT INTO country (id, name) VALUES (UUID_TO_BIN(UUID()), 'Колумбия');
INSERT INTO country (id, name) VALUES (UUID_TO_BIN(UUID()), 'Коморы');
INSERT INTO country (id, name) VALUES (UUID_TO_BIN(UUID()), 'Республика Конго');
INSERT INTO country (id, name) VALUES (UUID_TO_BIN(UUID()), 'Демократическая Республика Конго');
INSERT INTO country (id, name) VALUES (UUID_TO_BIN(UUID()), 'Корейская Народно-Демократическая Республика');
INSERT INTO country (id, name) VALUES (UUID_TO_BIN(UUID()), 'Республика Корея');
INSERT INTO country (id, name) VALUES (UUID_TO_BIN(UUID()), 'Коста-Рика');
INSERT INTO country (id, name) VALUES (UUID_TO_BIN(UUID()), 'Кот-д’Ивуар');
INSERT INTO country (id, name) VALUES (UUID_TO_BIN(UUID()), 'Куба');
INSERT INTO country (id, name) VALUES (UUID_TO_BIN(UUID()), 'Кувейт');
INSERT INTO country (id, name) VALUES (UUID_TO_BIN(UUID()), 'Лаос');